name: Test

on:
  push:
    branches:
    - main
  pull_request:
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-elixir@v1
      with:
        otp-version: '22.3'
        elixir-version: '1.10.0'

    - name: Get Dependencies
      run: mix deps.get

    - name: Run Tests
      run: mix test
      env:
        MIX_ENV: test
